# Generated by Django 5.1.4 on 2025-02-06 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='employee', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('work_mode', models.CharField(choices=[('on_site', 'On Site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='on_site', help_text='Work mode for the vacancy.', max_length=10)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(choices=[('anyone', 'Anyone'), ('tenth', 'Tenth'), ('diploma/twelfth', 'Diploma/Twelfth'), ('graduation', 'Graduation'), ('postgraduation', 'Post Graduation')], default='anyone', max_length=20)),
                ('total_openings', models.PositiveIntegerField(default=1)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
