# Generated by Django 5.1.4 on 2025-02-08 08:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume_required',
            field=models.BooleanField(default=False, help_text='Indicates if a resume is required for the application.'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='expire_date',
            field=models.DateField(blank=True, help_text='Last date for applications.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 2, 8))]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='total_openings',
            field=models.PositiveIntegerField(default=1, help_text='Number of available positions.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
