# Generated by Django 5.1.4 on 2025-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='credit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='gdp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
