# Generated by Django 5.1.4 on 2025-02-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_company_employerprofile_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('tenth', 'Tenth'), ('diploma/twelfth', 'Diploma/Twelfth'), ('graduation', 'Graduation'), ('postgraduation', 'Post Graduation')], default='anyone', max_length=20),
        ),
    ]
